name: sleap_pip

channels:
  - conda-forge
  - anaconda

dependencies:
  - python ==3.7.12
  - pip
  - pip:
    - 'sleap[dev] @ file:///home/talmolab/sleap-estimates-animal-poses/pull-requests/sleap/dist/sleap-1.3.2-py3-none-any.whl'
